version: '3.8'

services:
  app:
    build: .
    container_name: node-crud-practice-app
    ports:
      - "5005:5005"
    env_file:
      - .env
    environment:
      - MONGO_URI=mongodb://mongo:27017/nodecrudapp  # override localhost
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mongo
      - redis
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped

  mongo:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:7
    container_name: redis-cache
    ports:
      - "6379:6379"

volumes:
  mongo-data:
